# Use the Google App Engine base image
FROM gcr.io/google-appengine/python

# Update pip
RUN /env/bin/python -m pip install --upgrade pip

# Copy application code to the container
COPY . /app

# Set the working directory
WORKDIR /app

# Install dependencies
RUN /env/bin/python -m pip install -r requirements.txt

# Your other instructions...

# Specify the command to run on container start
CMD ["gunicorn", "-b", ":$PORT", "app:app"]